# Generated by Django 5.2.9 on 2026-01-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="Odoo India", max_length=200),
                ),
                ("company_initials", models.CharField(default="OI", max_length=10)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="company/"),
                ),
                ("working_days_per_week", models.PositiveIntegerField(default=5)),
                (
                    "break_time_hours",
                    models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
                ),
            ],
            options={
                "verbose_name": "Company Settings",
                "verbose_name_plural": "Company Settings",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="login_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("hr", "HR Officer"),
                    ("employee", "Employee"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
