# Generated by Django 5.2.9 on 2026-01-03 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employee_about_me_employee_bank_account_and_more"),
        ("leaves", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Attachment for sick leave certificate, etc.",
                null=True,
                upload_to="leave_attachments/",
            ),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="category",
            field=models.CharField(
                choices=[
                    ("paid", "Paid Time Off"),
                    ("sick", "Sick Leave"),
                    ("unpaid", "Unpaid Leave"),
                ],
                default="paid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="requires_attachment",
            field=models.BooleanField(
                default=False, help_text="Requires document (e.g., medical certificate)"
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="LeaveAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "allocated_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "used_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_allocations",
                        to="employees.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leaves.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["year", "leave_type__name"],
                "unique_together": {("employee", "leave_type", "year")},
            },
        ),
    ]
