# Generated by Django 5.2.9 on 2026-01-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payslip",
            old_name="medical_allowance",
            new_name="fixed_allowance",
        ),
        migrations.RenameField(
            model_name="payslip",
            old_name="other_allowances",
            new_name="lta",
        ),
        migrations.RenameField(
            model_name="payslip",
            old_name="tax_deduction",
            new_name="performance_bonus",
        ),
        migrations.RenameField(
            model_name="payslip",
            old_name="transport_allowance",
            new_name="professional_tax",
        ),
        migrations.RemoveField(
            model_name="salarystructure",
            name="basic_salary",
        ),
        migrations.RemoveField(
            model_name="salarystructure",
            name="hra",
        ),
        migrations.RemoveField(
            model_name="salarystructure",
            name="medical_allowance",
        ),
        migrations.RemoveField(
            model_name="salarystructure",
            name="other_allowances",
        ),
        migrations.RemoveField(
            model_name="salarystructure",
            name="pf_deduction",
        ),
        migrations.RemoveField(
            model_name="salarystructure",
            name="tax_deduction",
        ),
        migrations.RemoveField(
            model_name="salarystructure",
            name="transport_allowance",
        ),
        migrations.AddField(
            model_name="payslip",
            name="monthly_wage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payslip",
            name="standard_allowance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payslip",
            name="unpaid_leave_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payslip",
            name="unpaid_leave_deduction",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="basic_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="Basic as % of wage (e.g., 50)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="break_time_hours",
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="fixed_allowance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Any other fixed allowance",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="hra_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="HRA as % of Basic (e.g., 50)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="lta_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=8.33,
                help_text="LTA as % of wage",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="monthly_wage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total monthly wage",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="performance_bonus_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=8.33,
                help_text="Performance bonus as % of wage",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="pf_employee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=12.0,
                help_text="PF Employee contribution % of Basic",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="pf_employer_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=12.0,
                help_text="PF Employer contribution % of Basic",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="professional_tax",
            field=models.DecimalField(
                decimal_places=2,
                default=200,
                help_text="Fixed professional tax deduction",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="standard_allowance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Fixed standard allowance",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="working_days_per_week",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
