# Generated by Django 5.2.9 on 2026-01-03 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_rename_medical_allowance_payslip_fixed_allowance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Software Engineer Structure",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "basic_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Basic as % of wage (e.g., 50)",
                        max_digits=5,
                    ),
                ),
                (
                    "hra_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="HRA as % of Basic (e.g., 50)",
                        max_digits=5,
                    ),
                ),
                (
                    "lta_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.33,
                        help_text="LTA as % of wage",
                        max_digits=5,
                    ),
                ),
                (
                    "pf_employee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=12.0,
                        help_text="PF Employee contribution % of Basic",
                        max_digits=5,
                    ),
                ),
                (
                    "pf_employer_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=12.0,
                        help_text="PF Employer contribution % of Basic",
                        max_digits=5,
                    ),
                ),
                (
                    "standard_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fixed standard allowance",
                        max_digits=10,
                    ),
                ),
                (
                    "professional_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=200,
                        help_text="Fixed professional tax deduction",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="salarystructure",
            name="basic_percent",
        ),
        migrations.RemoveField(
            model_name="salarystructure",
            name="hra_percent",
        ),
        migrations.RemoveField(
            model_name="salarystructure",
            name="lta_percent",
        ),
        migrations.RemoveField(
            model_name="salarystructure",
            name="pf_employee_percent",
        ),
        migrations.RemoveField(
            model_name="salarystructure",
            name="pf_employer_percent",
        ),
        migrations.RemoveField(
            model_name="salarystructure",
            name="professional_tax",
        ),
        migrations.RemoveField(
            model_name="salarystructure",
            name="standard_allowance",
        ),
        migrations.AlterField(
            model_name="salarystructure",
            name="fixed_allowance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Any other fixed allowance unique to this person",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="salarystructure",
            name="monthly_wage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total monthly wage for this employee",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="salarystructure",
            name="performance_bonus_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Performance bonus as % of wage (Unique per person)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="structures",
                to="payroll.salarytemplate",
            ),
        ),
    ]
